In this file, I will take care of the data transformation, cleaning steps and make the data for training

# Importing Libraries and Setup

In [3]:
import pandas as pd
from pathlib import Path
import sys
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.base import BaseEstimator, TransformerMixin
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
import joblib

In [4]:
current_dir = Path.cwd().parent
sys.path.append(str(current_dir))
from src.config import RAW_DATA_DIR, PROCESSED_DATA_DIR, MODEL_DIR

In [5]:
TRAIN_DATA = RAW_DATA_DIR / "strat_train.csv"
TEST_DATA = RAW_DATA_DIR / "strat_test.csv"
OUTPUT_FILE_X = PROCESSED_DATA_DIR / "housing_prepared_x.pkl"
OUTPUT_FILE_Y = PROCESSED_DATA_DIR / "housing_labels.pkl"

In [6]:
linear_pkl = MODEL_DIR / "lin_reg_v1.pkl"
forest_pkl = MODEL_DIR / "random_forest_v1.pkl"
tree_pkl = MODEL_DIR / "decision_tree_v1.pkl"
svr_pkl = MODEL_DIR / "svr_v1.pkl"
Pipeline_path = MODEL_DIR / "full_pipeline.pkl"

## Load the data

In [7]:
strat_train = pd.read_csv(TRAIN_DATA)

In [8]:
strat_train.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-121.46,38.52,29.0,3873.0,797.0,2237.0,706.0,2.1736,72100.0,INLAND
1,-117.23,33.09,7.0,5320.0,855.0,2015.0,768.0,6.3373,279600.0,NEAR OCEAN
2,-119.04,35.37,44.0,1618.0,310.0,667.0,300.0,2.8750,82700.0,INLAND
3,-117.13,32.75,24.0,1877.0,519.0,898.0,483.0,2.2264,112500.0,NEAR OCEAN
4,-118.70,34.28,27.0,3536.0,646.0,1837.0,580.0,4.4964,238300.0,<1H OCEAN

In [9]:
strat_train.shape

(16512, 10)

## Split the x and y

In [10]:
housing_train = strat_train.drop("median_house_value", axis=1)

In [11]:
housing_train_label = strat_train["median_house_value"].copy()

# Data Cleaning

## Simple Imputer

In [12]:
imputer = SimpleImputer(strategy="median")

In [13]:
housing_num = housing_train.drop("ocean_proximity", axis=1)

In [14]:
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [15]:
imputer.statistics_

array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [16]:
housing_num.median().values

array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [17]:
train_x = imputer.transform(housing_num)  # the result is a numpy array

In [18]:
housing_tr = pd.DataFrame(train_x, columns=housing_num.columns)

In [19]:
housing_tr.info()

<class 'pandas.DataFrame'>
RangeIndex: 16512 entries, 0 to 16511
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           16512 non-null  float64
 1   latitude            16512 non-null  float64
 2   housing_median_age  16512 non-null  float64
 3   total_rooms         16512 non-null  float64
 4   total_bedrooms      16512 non-null  float64
 5   population          16512 non-null  float64
 6   households          16512 non-null  float64
 7   median_income       16512 non-null  float64
dtypes: float64(8)
memory usage: 1.0 MB

## Label encoder

In [20]:
encoder = LabelEncoder()
housing_cat = housing_train["ocean_proximity"]

In [21]:
housing_cat_encoded = encoder.fit_transform(housing_cat)

In [22]:
housing_cat_encoded

array([1, 4, 1, ..., 0, 0, 1], shape=(16512,))

In [23]:
encoder.classes_

array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
      dtype=object)

## OneHotEncoding

In [24]:
cat_encoder = OneHotEncoder()

In [25]:
housing_cat_1hot = cat_encoder.fit_transform(housing_cat.values.reshape(-1, 1))

In [26]:
housing_cat_1hot

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 16512 stored elements and shape (16512, 5)>

In [27]:
# After onehot encoding we get a matrix with thousands of columns, and the matrix is full of zeros except for a single 1 per row.

housing_cat_1hot.toarray()

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]], shape=(16512, 5))

In [28]:
cat_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

## Custom Transformers

In [29]:
housing_train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-121.46,38.52,29.0,3873.0,797.0,2237.0,706.0,2.1736,INLAND
1,-117.23,33.09,7.0,5320.0,855.0,2015.0,768.0,6.3373,NEAR OCEAN
2,-119.04,35.37,44.0,1618.0,310.0,667.0,300.0,2.8750,INLAND
3,-117.13,32.75,24.0,1877.0,519.0,898.0,483.0,2.2264,NEAR OCEAN
4,-118.70,34.28,27.0,3536.0,646.0,1837.0,580.0,4.4964,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
16507,-117.07,33.03,14.0,6665.0,1231.0,2026.0,1001.0,5.0900,<1H OCEAN
16508,-121.42,38.51,15.0,7901.0,1422.0,4769.0,1418.0,2.8139,INLAND
16509,-122.72,38.44,48.0,707.0,166.0,458.0,172.0,3.1797,<1H OCEAN
16510,-122.70,38.31,14.0,3155.0,580.0,1208.0,501.0,4.1964,<1H OCEAN
16511,-122.14,39.97,27.0,1079.0,222.0,625.0,197.0,3.1319,INLAND

In [30]:
rooms_ix, bedrooms_ix, population_ix, households_ix = 3, 4, 5, 6

In [31]:
class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_room=True):  # no *args or **kargs
        self.add_bedrooms_per_room = add_bedrooms_per_room

    def fit(self, X, y=None):
        return self  # nothing else to do

    def transform(self, X, y=None):
        rooms_per_household = X[:, rooms_ix] / X[:, households_ix]
        population_per_household = X[:, population_ix] / X[:, households_ix]
        if self.add_bedrooms_per_room:
            bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
            return np.c_[
                X, rooms_per_household, population_per_household, bedrooms_per_room
            ]
        else:
            return np.c_[X, rooms_per_household, population_per_household]

In [32]:
attr_adder = CombinedAttributesAdder(add_bedrooms_per_room=False)
housing_extra_attribs = attr_adder.transform(housing_train.values)

In [33]:
housing_extra_attribs

array([[-121.46, 38.52, 29.0, ..., 'INLAND', 5.485835694050992,
        3.168555240793201],
       [-117.23, 33.09, 7.0, ..., 'NEAR OCEAN', 6.927083333333333,
        2.6236979166666665],
       [-119.04, 35.37, 44.0, ..., 'INLAND', 5.3933333333333335,
        2.223333333333333],
       ...,
       [-122.72, 38.44, 48.0, ..., '<1H OCEAN', 4.1104651162790695,
        2.6627906976744184],
       [-122.7, 38.31, 14.0, ..., '<1H OCEAN', 6.297405189620759,
        2.411177644710579],
       [-122.14, 39.97, 27.0, ..., 'INLAND', 5.477157360406092,
        3.1725888324873095]], shape=(16512, 11), dtype=object)

## Pipelines

In [34]:
num_pipeline = Pipeline(
    [
        ("imputer", SimpleImputer(strategy="median")),
        ("attribs_adder", CombinedAttributesAdder()),
        ("std_scaler", StandardScaler()),
    ]
)
housing_num_tr = num_pipeline.fit_transform(housing_num)

In [35]:
num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]

In [36]:
num_attribs

['longitude',
 'latitude',
 'housing_median_age',
 'total_rooms',
 'total_bedrooms',
 'population',
 'households',
 'median_income']

In [37]:
cat_attribs

['ocean_proximity']

In [38]:
full_pipeline = ColumnTransformer(
    [
        ("num", num_pipeline, num_attribs),
        ("cat", OneHotEncoder(), cat_attribs),
    ]
)
housing_prepared = full_pipeline.fit_transform(housing_train)

In [39]:
joblib.dump(full_pipeline, Pipeline_path)

['C:\\Users\\nairs\\OneDrive\\Documents\\Surabhi\\Projects\\investment_analysis\\models\\full_pipeline.pkl']

## Save the X and Y

In [40]:
joblib.dump(housing_prepared, OUTPUT_FILE_X)
joblib.dump(housing_train_label, OUTPUT_FILE_Y)

['C:\\Users\\nairs\\OneDrive\\Documents\\Surabhi\\Projects\\investment_analysis\\data\\processed\\housing_labels.pkl']

# Train the baseline model

## Linear Regression

In [75]:
lin_reg = LinearRegression()

In [76]:
lin_reg.fit(housing_prepared, housing_train_label)

LinearRegression()

## Decision tree

In [77]:
tree = DecisionTreeRegressor()

In [78]:
tree.fit(housing_prepared, housing_train_label)

DecisionTreeRegressor()

In [79]:
housing_predictions_tree = tree.predict(housing_prepared)

## Random Forest

In [80]:
forest_tree = RandomForestRegressor(random_state=42)

In [81]:
forest_tree.fit(housing_prepared, housing_train_label)

RandomForestRegressor(random_state=42)

In [82]:
housing_pred_forest = forest_tree.predict(housing_prepared)

## Support Vector regression

In [83]:
svm = SVR(kernel="rbf", C=1.0, epsilon=0.1)

In [84]:
svm.fit(housing_prepared, housing_train_label)

SVR()

In [85]:
housing_pred_svm = svm.predict(housing_prepared)

# Evaluation

## Basic LinReg Eval

In [86]:
some_data = housing_train.iloc[:5]
some__label = housing_train_label.iloc[:5]

In [87]:
some_data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-121.46,38.52,29.0,3873.0,797.0,2237.0,706.0,2.1736,INLAND
1,-117.23,33.09,7.0,5320.0,855.0,2015.0,768.0,6.3373,NEAR OCEAN
2,-119.04,35.37,44.0,1618.0,310.0,667.0,300.0,2.8750,INLAND
3,-117.13,32.75,24.0,1877.0,519.0,898.0,483.0,2.2264,NEAR OCEAN
4,-118.70,34.28,27.0,3536.0,646.0,1837.0,580.0,4.4964,<1H OCEAN

In [88]:
some_data_prepared = full_pipeline.transform(some_data)

In [89]:
print(f"Predictions: {lin_reg.predict(some_data_prepared)}")

Predictions: [ 85657.90192014 305492.60737488 152056.46122456 186095.70946094
 244550.67966089]

In [90]:
print(f"labels: {list(some__label)}")

labels: [72100.0, 279600.0, 82700.0, 112500.0, 238300.0]

#### RMSE

In [91]:
housing_predictions = lin_reg.predict(housing_prepared)

In [92]:
lin_rmse = root_mean_squared_error(housing_train_label, housing_predictions)

In [93]:
lin_rmse

68627.87390018745

### KFold Cross Validation

In [94]:
def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard deviation:", scores.std())

In [95]:
lin_scores = cross_val_score(
    lin_reg,
    housing_prepared,
    housing_train_label,
    scoring="neg_root_mean_squared_error",
    cv=10,
)

In [96]:
rmse_lin_scores = -lin_scores

In [97]:
display_scores(rmse_lin_scores)

Scores: [71762.76364394 64114.99166359 67771.17124356 68635.19072082
 66846.14089488 72528.03725385 73997.08050233 68802.33629334
 66443.28836884 70139.79923956]
Mean: 69104.07998247063
Standard deviation: 2880.3282098180584

## Decision tree

### RMSE

In [98]:
tree_rmse = root_mean_squared_error(housing_train_label, housing_predictions_tree)

In [99]:
tree_rmse

0.0

### K fold cross validation

In [100]:
scores = cross_val_score(
    tree,
    housing_prepared,
    housing_train_label,
    scoring="neg_root_mean_squared_error",
    cv=10,
)

In [101]:
rmse_scores = -scores

In [102]:
display_scores(rmse_scores)

Scores: [71770.69763001 70304.74879458 68309.53182138 72000.7146764
 71105.44820154 77097.85409342 72640.63907254 73392.64549254
 66733.10384326 71012.55591482]
Mean: 71436.7939540488
Standard deviation: 2668.847349079737

## Random forest

### RMSE

In [103]:
forest_rmse = root_mean_squared_error(housing_train_label, housing_pred_forest)

In [104]:
forest_rmse

18650.698705770003

### Kfold Validations

In [105]:
scores_forest = cross_val_score(
    forest_tree,
    housing_prepared,
    housing_train_label,
    scoring="neg_root_mean_squared_error",
    cv=10,
)

In [106]:
forest_rmse_cv = -scores_forest

In [107]:
display_scores(forest_rmse_cv)

Scores: [51559.63379638 48737.57100062 47210.51269766 51875.21247297
 47577.50470123 51863.27467888 52746.34645573 50065.1762751
 48664.66818196 54055.90894609]
Mean: 50435.58092066179
Standard deviation: 2203.3381412764606

## SVR

### RMSE

In [108]:
svm_rmse = root_mean_squared_error(housing_train_label, housing_pred_svm)

In [109]:
svm_rmse

118578.69234925653

### Kfold CV

In [110]:
scores_cvm = cross_val_score(
    svm,
    housing_prepared,
    housing_train_label,
    scoring="neg_root_mean_squared_error",
    cv=10,
)

In [111]:
svm_rmse_cv = -scores_cvm

In [112]:
display_scores(svm_rmse_cv)

Scores: [116729.13778306 120113.99351281 113925.04340616 120399.11878641
 114687.49942071 122785.64737282 119853.79338279 118280.31108193
 120230.82615529 118840.1885232 ]
Mean: 118584.55594251942
Standard deviation: 2609.6120823493407

# Save the model and config

## Linear Regression

In [113]:
experiment_forest = {
    "model_object": lin_reg,
    "cv_scores": rmse_lin_scores,
    "mean_rmse": rmse_lin_scores.mean(),
    "predictions": housing_predictions,
}

In [114]:
joblib.dump(experiment_forest, linear_pkl)

['C:\\Users\\nairs\\OneDrive\\Documents\\Surabhi\\Projects\\investment_analysis\\models\\lin_reg_v1.pkl']

## Decision tree

In [115]:
experiment_forest = {
    "model_object": forest_tree,
    "cv_scores": rmse_scores,
    "mean_rmse": rmse_scores.mean(),
    "predictions": housing_predictions_tree,
}

In [116]:
joblib.dump(experiment_forest, tree_pkl)

['C:\\Users\\nairs\\OneDrive\\Documents\\Surabhi\\Projects\\investment_analysis\\models\\decision_tree_v1.pkl']

## Random Forest

In [117]:
experiment_forest = {
    "model_object": forest_tree,
    "cv_scores": forest_rmse_cv,
    "mean_rmse": forest_rmse_cv.mean(),
    "predictions": housing_pred_forest,
}

In [118]:
joblib.dump(experiment_forest, forest_pkl)

['C:\\Users\\nairs\\OneDrive\\Documents\\Surabhi\\Projects\\investment_analysis\\models\\random_forest_v1.pkl']

## SVR

In [119]:
experiment_forest = {
    "model_object": svm,
    "cv_scores": svm_rmse_cv,
    "mean_rmse": svm_rmse_cv.mean(),
    "predictions": housing_pred_svm,
}

In [120]:
joblib.dump(experiment_forest, svr_pkl)

['C:\\Users\\nairs\\OneDrive\\Documents\\Surabhi\\Projects\\investment_analysis\\models\\svr_v1.pkl']